import type { Locale } from "@/lib/i18n/types";
import { translate } from "@/lib/i18n/utils";

/** Public schema tables that receive audit_emit_row (excludes audit_logs, login_history). */
export const AUDITED_TABLE_VALUES = [
  "users",
  "roles",
  "permissions",
  "departments",
  "countries",
  "governorates",
  "cities",
  "customers",
  "customer_addresses",
  "suppliers",
  "supplier_addresses",
  "material_category_mains",
  "material_category_subs",
  "product_category_mains",
  "product_category_subs",
  "products",
  "product_production_routes",
  "product_dimensions",
  "product_standard_boms",
  "materials",
  "material_unit_conversions",
  "manufactured_material_boms",
  "inquiries",
  "inquiry_items",
  "previews",
  "preview_items",
  "offers",
  "offer_items",
  "offer_negotiations",
  "contracts",
  "contract_items",
  "material_purchase_requisitions",
  "material_purchase_requisition_items",
  "material_purchase_orders",
  "material_purchase_order_items",
  "material_purchase_order_item_contract_items",
  "material_purchase_order_item_requisition_items",
  "material_purchase_receipts",
  "material_purchase_receipt_items",
  "supplier_invoices",
  "outsourcing_orders",
  "outsourcing_order_items",
  "outsourcing_receipts",
  "outsourcing_receipt_items",
  "supplier_quotation_emails",
  "deliveries",
  "delivery_items",
  "trips",
  "installations",
  "installation_items",
  "customer_receptions",
  "customer_reception_items",
  "service_agreements",
  "maintenance_orders",
  "maintenance_order_items",
  "maintenance_order_materials",
  "production_plans",
  "production_sub_department_managers",
  "production_plan_items",
  "production_plan_item_notes",
  "inventory_transactions",
  "inventory_transaction_items",
  "legacy_issue_permits",
  "legacy_issue_permit_items",
  "product_units",
  "product_purchase_orders",
  "product_purchase_order_items",
  "product_purchase_receipts",
  "product_purchase_receipt_items",
] as const;

export type AuditedTable = (typeof AUDITED_TABLE_VALUES)[number];

type TableLabel = { en: string; ar: string };

const AUDITED_TABLE_LABELS: Record<AuditedTable, TableLabel> = {
  users: { en: "Users", ar: "المستخدمون" },
  roles: { en: "Roles", ar: "الأدوار" },
  permissions: { en: "Permissions", ar: "الصلاحيات" },
  departments: { en: "Departments", ar: "الأقسام" },
  countries: { en: "Countries", ar: "الدول" },
  governorates: { en: "Governorates", ar: "المحافظات" },
  cities: { en: "Cities", ar: "المدن" },
  customers: { en: "Customers", ar: "العملاء" },
  customer_addresses: { en: "Customer Addresses", ar: "عناوين العملاء" },
  suppliers: { en: "Suppliers", ar: "الموردون" },
  supplier_addresses: { en: "Supplier Addresses", ar: "عناوين الموردين" },
  material_category_mains: { en: "Material Main Categories", ar: "التصنيفات الرئيسية للمواد" },
  material_category_subs: { en: "Material Sub Categories", ar: "التصنيفات الفرعية للمواد" },
  product_category_mains: { en: "Product Main Categories", ar: "التصنيفات الرئيسية للمنتجات" },
  product_category_subs: { en: "Product Sub Categories", ar: "التصنيفات الفرعية للمنتجات" },
  products: { en: "Products", ar: "المنتجات" },
  product_production_routes: { en: "Product Production Routes", ar: "مسارات إنتاج المنتجات" },
  product_dimensions: { en: "Product Dimensions", ar: "أبعاد المنتجات" },
  product_standard_boms: { en: "Product Standard BOMs", ar: "قوائم مواد المنتجات" },
  materials: { en: "Materials", ar: "المواد" },
  material_unit_conversions: { en: "Material Unit Conversions", ar: "تحويلات وحدات المواد" },
  manufactured_material_boms: { en: "Manufactured Material BOMs", ar: "قوائم مواد التصنيع" },
  inquiries: { en: "Inquiries", ar: "الاستفسارات" },
  inquiry_items: { en: "Inquiry Items", ar: "بنود الاستفسار" },
  previews: { en: "Previews", ar: "المعاينات" },
  preview_items: { en: "Preview Items", ar: "بنود المعاينة" },
  offers: { en: "Offers", ar: "عروض الأسعار" },
  offer_items: { en: "Offer Items", ar: "بنود العرض" },
  offer_negotiations: { en: "Offer Negotiations", ar: "مفاوضات العروض" },
  contracts: { en: "Contracts", ar: "العقود" },
  contract_items: { en: "Contract Items", ar: "بنود العقد" },
  material_purchase_requisitions: { en: "Material Purchase Requisitions", ar: "طلبات شراء الخامات" },
  material_purchase_requisition_items: { en: "Material Requisition Items", ar: "بنود طلب شراء الخامات" },
  material_purchase_orders: { en: "Material Purchase Orders", ar: "أوامر توريد الخامات" },
  material_purchase_order_items: { en: "Material Purchase Order Items", ar: "بنود أمر توريد الخامات" },
  material_purchase_order_item_contract_items: {
    en: "MPO Contract Allocations",
    ar: "تخصيصات العقد في أمر الخامات",
  },
  material_purchase_order_item_requisition_items: {
    en: "MPO Requisition Allocations",
    ar: "تخصيصات الطلب في أمر الخامات",
  },
  material_purchase_receipts: { en: "Material Purchase Receipts", ar: "إذون استلام الخامات" },
  material_purchase_receipt_items: { en: "Material Receipt Items", ar: "بنود إذن استلام الخامات" },
  supplier_invoices: { en: "Supplier Invoices", ar: "فواتير الموردين" },
  outsourcing_orders: { en: "Outsourcing Orders", ar: "أوامر التشغيل الخارجي" },
  outsourcing_order_items: { en: "Outsourcing Order Items", ar: "بنود أمر التشغيل الخارجي" },
  outsourcing_receipts: { en: "Outsourcing Receipts", ar: "إذون استلام التشغيل الخارجي" },
  outsourcing_receipt_items: { en: "Outsourcing Receipt Items", ar: "بنود إذن التشغيل الخارجي" },
  supplier_quotation_emails: { en: "Supplier Quotation Emails", ar: "رسائل طلب عروض الأسعار" },
  deliveries: { en: "Deliveries", ar: "التسليمات" },
  delivery_items: { en: "Delivery Items", ar: "بنود التسليم" },
  trips: { en: "Trips", ar: "المأموريات" },
  installations: { en: "Installations", ar: "التركيبات" },
  installation_items: { en: "Installation Items", ar: "بنود التركيب" },
  customer_receptions: { en: "Customer Receptions", ar: "التسلميات" },
  customer_reception_items: { en: "Reception Items", ar: "بنود التسليم" },
  service_agreements: { en: "Service Agreements", ar: "عقود الصيانة" },
  maintenance_orders: { en: "Maintenance Orders", ar: "أوامر الصيانة" },
  maintenance_order_items: { en: "Maintenance Order Items", ar: "بنود أمر الصيانة" },
  maintenance_order_materials: { en: "Maintenance Order Materials", ar: "مواد أمر الصيانة" },
  production_plans: { en: "Production Plans", ar: "خطط الإنتاج" },
  production_sub_department_managers: {
    en: "Production Sub-Department Managers",
    ar: "مديرو أقسام الإنتاج الفرعية",
  },
  production_plan_items: { en: "Production Plan Items", ar: "بنود خطة الإنتاج" },
  production_plan_item_notes: { en: "Production Plan Item Notes", ar: "ملاحظات بنود خطة الإنتاج" },
  inventory_transactions: { en: "Inventory Transactions", ar: "حركات المخزون" },
  inventory_transaction_items: { en: "Inventory Transaction Items", ar: "بنود حركة المخزون" },
  legacy_issue_permits: { en: "Legacy Issue Permits", ar: "أذونات الصرف المرحلية" },
  legacy_issue_permit_items: { en: "Legacy Issue Permit Items", ar: "بنود أذن الصرف المرحلي" },
  product_units: { en: "Product Units", ar: "وحدات المنتج" },
  product_purchase_orders: { en: "Product Purchase Orders", ar: "أوامر توريد المنتجات" },
  product_purchase_order_items: { en: "Product Purchase Order Items", ar: "بنود أمر توريد المنتجات" },
  product_purchase_receipts: { en: "Product Purchase Receipts", ar: "إذون استلام المنتجات" },
  product_purchase_receipt_items: { en: "Product Receipt Items", ar: "بنود إذن استلام المنتجات" },
};

export function getAuditedTableLabel(tableName: string, locale: Locale) {
  const label = AUDITED_TABLE_LABELS[tableName as AuditedTable];
  if (!label) return tableName;
  return translate(locale, label.en, label.ar);
}

export function getAuditedTableSelectData(locale: Locale) {
  return AUDITED_TABLE_VALUES.map((value) => ({
    value,
    label: getAuditedTableLabel(value, locale),
  })).sort((a, b) => a.label.localeCompare(b.label, locale));
}

export function isValidAuditedTable(tableName: string): tableName is AuditedTable {
  return AUDITED_TABLE_VALUES.includes(tableName as AuditedTable);
}
